const mongoose = require("mongoose");

const products = mongoose.Schema(
  {
    id: { type: Number },
    description: { type: String, required: true },
    price: { type: Number, required: true },
    state: { type: String, required: true },
  },
  {
    versionKey: false, // You should be aware of the outcome after set to false
    // add this if you want to avoid autogenerated __v field
  }
);

module.exports = mongoose.model("products", products);
